### ISSUE TITLE
ERROR: "unrecognized arguments" when the search term has multiple words

### ISSUE THREAD

**Issue by luisfelipesdn12** [ultralytics/flickr_scraper#2]
Hey! First of all: congrats for the api. Well, every time I try to search something with more than one word, like 'Albert Eistein' I'm having the issue below:

```cmd
\flickr_scraper-master>python flickr_scraper.py --search 'flat design' --n 10 --download
usage: flickr_scraper.py [-h] [--search SEARCH] [--n N] [--download]
flickr_scraper.py: error: unrecognized arguments: design'
```

It doesn't  happen when the search term is like 'Beatles'.

**Comment by luisfelipesdn12** [comment]
Oh! It worked here too! Thanks :)

**Comment by glenn-jocher** [comment]
Great! So I’m confused, was the problem the single quotes or something else?

**Comment by luisfelipesdn12** [comment]
Oh, I'm sorry. The problem was solved completely! I've reopened accidentally. Thanks :)

**Comment by glenn-jocher** [comment]
@luisfelipesdn12 no worries at all! I'm glad the issue got resolved. If you have any more questions or run into any other issues, feel free to ask.
