### ISSUE TITLE
Can this run in windows?

### ISSUE THREAD

**Issue by Iarkii** [ultralytics/flickr_scraper#3]

**Comment by glenn-jocher** [comment]
Yes?

**Comment by liuzaozao7799** [comment]
It seems not, I have tried yet...

**Comment by liuzaozao7799** [comment]
Yes, I have just tried.

**Comment by hankTrident** [comment]
hi glenn-jocher
i use the flickr_scraper.py 
but no images dir found why?
![54](https://user-images.githubusercontent.com/65845494/82799882-56bd5180-9ead-11ea-91e2-b8a00d49ff26.png)

**Comment by glenn-jocher** [comment]
@hankTrident see https://github.com/ultralytics/flickr_scraper#use
